# Generated by Django 2.2.10 on 2020-03-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_address_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominalledger',
            name='contra_address_id',
            field=models.IntegerField(null=True),
        ),
    ]
