# Generated by Django 5.0.10 on 2025-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_days_statement_settings'),
    ]

    operations = [
        migrations.RunSQL("""
            --------------------------------------------------------------------
            -- Before Altering column types, drop view referencing the column --
            -- After type change, recreate view (0009)                        --
            --------------------------------------------------------------------
            DROP VIEW "nominal_account_history";
        """),
        migrations.AlterField(
            model_name='addressnominalaccount',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='addressnominalaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allocationdetail',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='allocationdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalnominalaccount',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='globalnominalaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='integritytest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nominalaccounttype',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='nominalaccounttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nominalcontra',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='nominalcontra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nominalledger',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='nominalledger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nominalledgercredit',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='nominalledgercredit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nominalledgerdebit',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='nominalledgerdebit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statementlog',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='statementlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statementsettings',
            name='day',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
